### Comparing NoFool to Normal MNIST

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
mnist = pd.read_csv()

In [3]:
no_fool = pd.read_csv("../singularity_singlegpu_mnist-nofool-25trials_11-14.csv")

In [54]:
len(mnist)

140

In [4]:
len(no_fool)

400

In [5]:
no_fool.head()

,trial_id,pt_test_acc,tf_test_acc,average_res,time_this_iter_s,done,timesteps_total,episodes_total,training_iteration,experiment_id,...,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.learning_rate,config.dropout,config.epochs,config.batch_size
0,7e9e7844,0.369435,0.4390,0.404218,0.007671,True,NaN,NaN,2,657e9341b147456abf74aa49987c6eeb,...,thetagpu12,140.221.68.22,108.796603,0,2,"1_batch_size=486,dropout=0.8407,epochs=54,lear...",0.071030,0.840701,54,486
1,7fcf5760,0.237644,0.3081,0.272872,0.008078,True,NaN,NaN,2,0b66dce4cf854386a9afffdabba55b6e,...,thetagpu12,140.221.68.22,109.397163,0,2,"2_batch_size=315,dropout=0.87107,epochs=54,lea...",0.061605,0.871070,54,315
2,802224ea,0.185387,0.1258,0.155593,0.008964,True,NaN,NaN,2,fac4185f90964d069261557165475069,...,thetagpu12,140.221.68.22,135.075513,0,2,"3_batch_size=423,dropout=0.87777,epochs=76,lea...",0.090365,0.877773,76,423
3,804fa8fc,0.434533,0.5323,0.483416,0.008848,True,NaN,NaN,2,0ca0702f99d44c18af1bad7ed45e0c35,...,thetagpu12,140.221.68.22,144.893923,0,2,"4_batch_size=216,dropout=0.62036,epochs=70,lea...",0.090331,0.620362,70,216
4,80637eae,0.745158,0.8051,0.775129,0.009432,True,NaN,NaN,2,f18610b7f636400c89aca45d3464e512,...,thetagpu12,140.221.68.22,136.576412,0,2,"5_batch_size=317,dropout=0.47921,epochs=75,lea...",0.080110,0.479207,75,317

In [6]:
no_fool_sorted = no_fool.sort_values('average_res', ascending=False)
no_fool_sorted = no_fool_sorted.reset_index(drop=True)

In [50]:
mnist_sorted = mnist.sort_values('average_res', ascending=False)
mnist_sorted = mnist_sorted.reset_index(drop=True)

In [7]:
no_fool_sorted.head()

,trial_id,pt_test_acc,tf_test_acc,average_res,time_this_iter_s,done,timesteps_total,episodes_total,training_iteration,experiment_id,...,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.learning_rate,config.dropout,config.epochs,config.batch_size
0,ba4c9ce0,0.981378,0.9806,0.980989,0.007925,True,NaN,NaN,2,d4301e885d5f445c850950399c82c93f,...,thetagpu12,140.221.68.22,191.042043,0,2,"14_batch_size=308,dropout=0.26889,epochs=91,le...",0.000947,0.268886,91,308
1,8fda67d4,0.978629,0.9784,0.978514,0.009335,True,NaN,NaN,2,65f4334d5f344d5e9b7e0ce57b52ea1c,...,thetagpu12,140.221.68.22,171.577485,0,2,"11_batch_size=215,dropout=0.51882,epochs=92,le...",0.001991,0.518818,92,215
2,79dc9932,0.978243,0.9786,0.978422,0.011660,True,NaN,NaN,2,a81cbaeb852e4979b52c8e33ac4e8ae3,...,thetagpu12,140.221.68.22,126.465294,0,2,"14_batch_size=325,dropout=0.43285,epochs=86,le...",0.006084,0.432850,86,325
3,23992bda,0.977615,0.9774,0.977507,0.011948,True,NaN,NaN,2,523b2aac115c4f7fb823d57545b1f7dc,...,thetagpu12,140.221.68.22,85.705043,0,2,"9_batch_size=367,dropout=0.56818,epochs=58,lea...",0.001214,0.568180,58,367
4,4a869e52,0.977361,0.9776,0.977480,0.008322,True,NaN,NaN,2,366cd5eead6a4ddf9cf7877dbd3a1386,...,thetagpu12,140.221.68.22,121.316652,0,2,"5_batch_size=206,dropout=0.32134,epochs=63,lea...",0.007122,0.321343,63,206

In [52]:
mnist_sorted.head()

,trial_id,pt_test_acc,pt_uniform_accuracy,pt_gaussian_accuracy,pt_saltandpepper_accuracy,pt_spatial_accuracy,tf_test_acc,tf_uniform_accuracy,tf_gaussian_accuracy,tf_saltandpepper_accuracy,...,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.learning_rate,config.dropout,config.epochs,config.batch_size
0,fe32ae60,0.980269,0.980071,0.980117,0.978531,0.0,0.9801,0.980289,0.980304,0.978883,...,thetagpu16,140.221.68.26,267.512279,0,2,"10_batch_size=174,dropout=0.25689,epochs=22,le...",0.003000,0.256887,22,174
1,132ffee0,0.976167,0.975703,0.975749,0.973801,0.0,0.9759,0.974995,0.975170,0.972751,...,thetagpu16,140.221.68.26,458.945885,0,2,"6_batch_size=128,dropout=0.44812,epochs=72,lea...",0.006307,0.448118,72,128
2,8a7f6e40,0.970294,0.970002,0.970025,0.968126,0.0,0.9692,0.968912,0.969035,0.967059,...,thetagpu16,140.221.68.26,1322.525426,0,2,"4_batch_size=29,dropout=0.61108,epochs=25,lear...",0.002777,0.611076,25,29
3,132e5d92,0.965700,0.964469,0.964631,0.962392,0.0,0.9694,0.968685,0.968700,0.966154,...,thetagpu16,140.221.68.26,588.657999,0,2,"5_batch_size=80,dropout=0.32416,epochs=47,lear...",0.012924,0.324156,47,80
4,3647d05c,0.968197,0.967295,0.967448,0.965058,0.0,0.9656,0.964638,0.964890,0.962019,...,thetagpu16,140.221.68.26,606.855360,0,2,"2_batch_size=86,dropout=0.49021,epochs=66,lear...",0.010307,0.490205,66,86