### Comparing NoFool to Normal MNIST

In [11]:
import pandas as pd

In [41]:
mnist = pd.read_csv("../singularity_singlegpu_mnist_10trials_11-13_fixed.csv")

In [42]:
no_fool = pd.read_csv("../singularity_singlegpu_mnist-nofool_10trials_11-13_fixed.csv")

In [43]:
len(mnist)

60

In [44]:
len(no_fool)

140

In [45]:
no_fool.head()

,trial_id,pt_test_acc,tf_test_acc,average_res,time_this_iter_s,done,timesteps_total,episodes_total,training_iteration,experiment_id,...,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.learning_rate,config.dropout,config.epochs,config.batch_size
0,c2e1b62c,0.657469,0.6700,0.663734,0.007899,True,NaN,NaN,2,75cb53aacfc845709020722f6c14d1d6,...,thetagpu13,140.221.68.23,84.444551,0,2,"1_batch_size=392,dropout=0.70595,epochs=45,lea...",0.073741,0.705950,45,392
1,c30609aa,0.900028,0.9112,0.905614,0.006450,True,NaN,NaN,2,56e2d2ddd3b4447f995edfe710627d56,...,thetagpu13,140.221.68.23,151.036690,0,2,"2_batch_size=329,dropout=0.47194,epochs=98,lea...",0.057700,0.471941,98,329
2,c3093198,0.865802,0.8903,0.878051,0.009371,True,NaN,NaN,2,c602f6c61b7a4c558a8465b3862d4fba,...,thetagpu13,140.221.68.23,158.487826,0,2,"3_batch_size=311,dropout=0.62427,epochs=97,lea...",0.048877,0.624272,97,311
3,c30b0bbc,0.667911,0.6918,0.679855,0.008520,True,NaN,NaN,2,c3463982e88f4847a9214a01ab9a22d6,...,thetagpu13,140.221.68.23,109.879301,0,2,"4_batch_size=210,dropout=0.73358,epochs=55,lea...",0.052130,0.733581,55,210
4,c30cc57e,0.774563,0.7160,0.745282,0.008483,True,NaN,NaN,2,7b61128a7858463a91c76a3be8d3298c,...,thetagpu13,140.221.68.23,92.316003,0,2,"5_batch_size=399,dropout=0.64868,epochs=53,lea...",0.071994,0.648680,53,399

In [49]:
no_fool_sorted = no_fool.sort_values('average_res', ascending=False)
no_fool_sorted = no_fool_sorted.reset_index(drop=True)

In [50]:
mnist_sorted = mnist.sort_values('average_res', ascending=False)
mnist_sorted = mnist_sorted.reset_index(drop=True)

In [51]:
no_fool_sorted.head()

,trial_id,pt_test_acc,tf_test_acc,average_res,time_this_iter_s,done,timesteps_total,episodes_total,training_iteration,experiment_id,...,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.learning_rate,config.dropout,config.epochs,config.batch_size
0,d737008a,0.979507,0.9813,0.980403,0.007831,True,NaN,NaN,2,ed8860162f414ae4a83f83a03d0d8b09,...,thetagpu13,140.221.68.23,103.549912,0,2,"1_batch_size=312,dropout=0.46398,epochs=65,lea...",0.002032,0.463976,65,312
1,fca574e4,0.979464,0.9804,0.979932,0.007350,True,NaN,NaN,2,fd261ae24dd64d8595905df2453efd4b,...,thetagpu13,140.221.68.23,110.291693,0,2,"8_batch_size=224,dropout=0.48711,epochs=64,lea...",0.001926,0.487106,64,224
2,fca3656e,0.977771,0.9805,0.979136,0.030291,True,NaN,NaN,2,3b8de45bd27c4945b74c03e84ad01029,...,thetagpu13,140.221.68.23,330.653174,0,2,"7_batch_size=48,dropout=0.48534,epochs=70,lear...",0.000834,0.485337,70,48
3,5ff34eb0,0.978792,0.9775,0.978146,0.008665,True,NaN,NaN,2,37e4b0b621614407ae133633433881b0,...,thetagpu13,140.221.68.23,84.479182,0,2,"1_batch_size=291,dropout=0.21942,epochs=54,lea...",0.007132,0.219415,54,291
4,c49ab616,0.973692,0.9776,0.975646,0.008765,True,NaN,NaN,2,ca7b1963ed254745affbeab068c2f27f,...,thetagpu13,140.221.68.23,131.227664,0,2,"3_batch_size=190,dropout=0.28739,epochs=73,lea...",0.010314,0.287390,73,190

In [52]:
mnist_sorted.head()

,trial_id,pt_test_acc,pt_uniform_accuracy,pt_gaussian_accuracy,pt_saltandpepper_accuracy,pt_spatial_accuracy,tf_test_acc,tf_uniform_accuracy,tf_gaussian_accuracy,tf_saltandpepper_accuracy,...,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.learning_rate,config.dropout,config.epochs,config.batch_size
0,fe32ae60,0.980269,0.980071,0.980117,0.978531,0.0,0.9801,0.980289,0.980304,0.978883,...,thetagpu16,140.221.68.26,267.512279,0,2,"10_batch_size=174,dropout=0.25689,epochs=22,le...",0.003000,0.256887,22,174
1,132ffee0,0.976167,0.975703,0.975749,0.973801,0.0,0.9759,0.974995,0.975170,0.972751,...,thetagpu16,140.221.68.26,458.945885,0,2,"6_batch_size=128,dropout=0.44812,epochs=72,lea...",0.006307,0.448118,72,128
2,8a7f6e40,0.970294,0.970002,0.970025,0.968126,0.0,0.9692,0.968912,0.969035,0.967059,...,thetagpu16,140.221.68.26,1322.525426,0,2,"4_batch_size=29,dropout=0.61108,epochs=25,lear...",0.002777,0.611076,25,29
3,132e5d92,0.965700,0.964469,0.964631,0.962392,0.0,0.9694,0.968685,0.968700,0.966154,...,thetagpu16,140.221.68.26,588.657999,0,2,"5_batch_size=80,dropout=0.32416,epochs=47,lear...",0.012924,0.324156,47,80
4,3647d05c,0.968197,0.967295,0.967448,0.965058,0.0,0.9656,0.964638,0.964890,0.962019,...,thetagpu16,140.221.68.26,606.855360,0,2,"2_batch_size=86,dropout=0.49021,epochs=66,lear...",0.010307,0.490205,66,86